[package]
name = "bricksdb"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = "0.27"
bitvec = "1"
boxcar = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "6.1.0"
log = "0.4"
zstd = "0.13"
rand = "0.8"
[dev-dependencies]
tempfile = "3"